#!/bin/bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

source "$(dirname "$0")/config"

docker pull rhub/rocker-jenkins

mkdir -p "$PLUGIN_DATA_ROOT" || \
    echo "Failed to create $PLUGIN_DATA_ROOT directory"
chown dokku:dokku "$PLUGIN_DATA_ROOT"
